package net.simplelib;

import net.minecraft.init.Blocks;
import net.minecraftforge.fml.common.Loader;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.ModMetadata;
import net.minecraftforge.fml.common.SidedProxy;
import net.minecraftforge.fml.common.event.*;
import net.minecraftforge.fml.common.network.NetworkCheckHandler;
import net.minecraftforge.fml.relauncher.Side;
import net.simplelib.common.CommonLogger;
import net.simplelib.common.registry.RegistryBufferManager;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import java.util.Map;

@Mod(modid = HelperMod.MODID, name = HelperMod.NAME, version = HelperMod.VERSION, useMetadata = true)
public class HelperMod
{
	public static final String MODID = "helper", NAME = "Helper", VERSION = "beta 0.7";

	public static final boolean DEBUG_MOD;

	@Mod.Metadata(MODID)
	public static ModMetadata metadata;

	@Mod.Instance(MODID)
	public static HelperMod instance;

	public static final Logger LOG = LogManager.getLogger("test");

	@SidedProxy(modId = MODID, serverSide = "net.simplelib.CommonProxy", clientSide = "net.simplelib.ClientProxy")
	public static CommonProxy proxy;

	@Mod.EventHandler
	public void construct(FMLConstructionEvent event)
	{
		CommonLogger.init();
		if (DEBUG_MOD)
			CommonLogger.info("Detected that this is a development environment. Debug mode on.");
		RegistryHelper.INSTANCE.container = Loader.instance().activeModContainer();
		RegistryBufferManager.instance().load(event.getASMHarvestedData());
		RegistryBufferManager.instance().invoke(event);
	}

	@Mod.EventHandler
	public void preInit(FMLPreInitializationEvent event)
	{
//		event.getModConfigurationDirectory()
		RegistryBufferManager.instance().invoke(event);
	}

	@Mod.EventHandler
	public void init(FMLInitializationEvent event)
	{
		metadata.autogenerated = false;
		metadata.description = "A mod that can simplify the mod registrant.";
		metadata.url = "https://github.com/ci010/SimpleLib";
		metadata.authorList.add(0, "ci010");
		metadata.updateUrl = "https://github.com/ci010/SimpleLib/releases";

		//TODO remove this test code
		RegistryHelper.INSTANCE.registerSittableBlock(Blocks.brick_stairs);
		RegistryBufferManager.instance().invoke(event);
	}

	@Mod.EventHandler
	public void postInit(FMLPostInitializationEvent event) {RegistryBufferManager.instance().invoke(event);}

	@Mod.EventHandler
	public void complete(FMLLoadCompleteEvent event)
	{
		RegistryBufferManager.instance().invoke(event);
		RegistryHelper.INSTANCE.close();
	}

	@Mod.EventHandler
	void serverAboutStart(FMLServerAboutToStartEvent event) {RegistryBufferManager.instance().invoke(event);}

	@Mod.EventHandler
	public void serverStarting(FMLServerStartingEvent event)
	{
		RegistryBufferManager.instance().invoke(event);
	}

	@Mod.EventHandler
	public void serverStarted(FMLServerStartedEvent event)
	{
		RegistryBufferManager.instance().invoke(event);
		RegistryBufferManager.close();
	}

	@NetworkCheckHandler
	public boolean acceptModList(Map<String, String> modList, Side side)
	{
		for (Map.Entry<String, String> entry : modList.entrySet())
		{
			System.out.println(entry.getKey());
			System.out.println(entry.getValue());
		}
		return true;
	}

	static
	{
		boolean fail = false;
		try
		{
			Class.forName("net.minecraftforge.gradle.GradleStartCommon");
		}
		catch (ClassNotFoundException e)
		{
			fail = true;
		}
		DEBUG_MOD = !fail;
	}
}
